---
pve_api_host: "192.168.1.200"
pve_api_user: "ansible@pve"
pve_api_token_id: "ansible"
pve_api_token_secret: "{{ vault_pve_token_secret }}"
pve_node: "pve1"
pve_api_port: 8006

# ===== Defaults =====
pve_bridge_default: "vmbr0"
pve_ipconfig0_default: "ip=dhcp"
pve_ciuser_default: "ansible"
pve_searchdomain_default: "local"

# ===== Template source =====
pve_template_vmid: 9011
pve_clone_full: true

ci_user: "debian"
ci_timezone: "Europe/Bratislava"
ci_ssh_pubkey_path: "~/.ssh/id_ed25519.pub"

