pve_api_host: "192.168.1.200"
pve_api_user: "ansible@pve"
pve_api_token_id: "terraform"
pve_api_token_secret: "{{ vault_pve_token_secret }}"
pve_node: "pve1"

pve_storage_disk: "local-lvm"
tmpl_vmid: 9000
tmpl_name: "debian-12-cloudinit"
tmpl_memory: 2048
tmpl_cores: 2
tmpl_disk_gb: 16
tmpl_bridge: "vmbr0"

debian_cloudimg_url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
debian_cloudimg_filename: "debian-12-genericcloud-amd64.qcow2"

ci_user: "debian"
ci_timezone: "Europe/Bratislava"
ci_ssh_pubkey_path: "~/.ssh/id_ed25519.pub"
