---
# ===== Proxmox API (token) =====
proxmox_api_host: "pve1"
proxmox_api_user: "ansible@pve"
proxmox_api_token_id: "ansible"
proxmox_api_token_secret: "{{ vault_pve_api_token_secret }}"
proxmox_validate_certs: false

# ===== Template source =====
pve_template_vmid: 9001
pve_clone_full: true

# ===== Defaults =====
pve_bridge_default: "vmbr0"
pve_ipconfig0_default: "ip=dhcp"
pve_ciuser_default: "ansible"
pve_searchdomain_default: "local"
