ansible_user: ansible

# workstations typicky vyžadujú sudo
ansible_become: true
ansible_become_method: sudo


ansible_managed_user: "ansible"
ansible_managed_groups: ["sudo"]
ansible_sudo_nopasswd: true
