pve_node: pve
vmid: 201
vm_name: aufik
vm_type: instance
os_family: debian

clone_from_template_vmid: 9001

pve_bridge: vmbr10

# keď po deployi dostane IP, toto je link na reálny SSH host
ssh_host: "{{ vm_name }}.{{ domain_name }}"

# hw 

pve_cores: 4
pve_memory: 4096
pve_balloon: 0
pve_agent: 1
pve_onboot: 1
pve_boot_order: "scsi0;net0"
pve_scsihw: "virtio-scsi-single"

pve_tags: "debian,secure"
pve_description: "Debian instance for aufik"

domain_name: joseph4lansolo.xyz


# DebOps docker_server
docker_server__enabled: true

# (voliteľné) povoliť používateľovi ovládať docker bez sudo
docker_server__admins:
  - "ansible"

# (voliteľné) docker daemon hardening baseline
docker_server__daemon_options:
  userland-proxy: false
  live-restore: true
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"