# roles/pve_vm_provision_kvm/meta/main.yml
---
dependencies: []
galaxy_info:
  role_name: pve_vm_provision_kvm
  author: joseph
  description: Clone + cloud-init configure + lifecycle via community.proxmox.proxmox_kvm
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: ["bookworm", "bullseye"]