ufw_bundles:
  base:
    - { rule: allow, port: "22", proto: tcp, comment: "ssh" }

  web:
    - { rule: allow, port: "80", proto: tcp, comment: "http" }
    - { rule: allow, port: "443", proto: tcp, comment: "https" }

  wireguard:
    - { rule: allow, port: "51820", proto: udp, comment: "wg" }
