users__accounts:

  - name: 'joseph'
    local: false
    uid: 1099
    group: 'joseph'
    groups: [ 'sudo' ]
    shell: '/bin/bash'
    home: '/home/joseph'
    create_home: true
    state: 'present'

users__groups:
  - name: 'sudo'
    local: false
    state: 'present'