# group_vars/all/users.yml
users_manage:
  - name: ansible
    uid: 1100
    groups: [sudo]
    shell: /bin/bash
    create_home: true
    sudo_nopasswd: true

  - name: joseph
    uid: 1000
    groups: [sudo]
    shell: /bin/bash
    create_home: true
    sudo_nopasswd: false