sshd_password_auth: "no"
sshd_permit_root_login: "no"          # po bootstrap
sshd_pubkey_auth: "yes"
sshd_kbd_interactive: "no"
sshd_x11_forwarding: "no"
sshd_allow_users: ["ansible", "joseph"]
sshd_client_alive_interval: 300
sshd_client_alive_countmax: 2
sshd_max_auth_tries: 3
sshd_login_grace_time: 20
