---
- name: Bootstrap access and ansible user
  hosts: servers
  become: true
  become_method: su
  become_user: joseph

  gather_facts: true

  roles:
    - role: ssh_key_setup_v1
    - role: user_setup_v1