---
- name: Bootstrap access and ansible user
  hosts: pve
  become: true
  become_method: su
  become_user: ansible

  gather_facts: true

  roles:
    - role: ssh_key_setup_v1
    - role: sshd_hardening_s1_v1