---
- name: Ensure sshd_config.d exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Deploy sshd_config
  ansible.builtin.template:
    src: sshd_config_s1_v1.j2
    dest: /etc/ssh/sshd_config.d/10-ansible-hardening.conf
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  become: true
  notify: Validate and restart sshd